mqp-docker:
  image: thebanhammer/mqp-docker:latest
  name: mqp-${slug}
  ports:
    - ${port}:20808
  environment:
    - slug=${slug}
    - padName=${padName}
    - greet=${greet}
    - owner=${owner}
    - mpKey=${mpKey}
    - NPM_CONFIG_LOGLEVEL=info
    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - NODE_VERSION=4.2.4
