mqp-docker:
  image: thebanhammer/mqp-docker:latest
  ports:
    - ${port}:20808
  environment:
    - slug=${slug}
    - padName=${padName}
    - greet=${greet}
    - owner=${owner}
    - mpKey=${mpKey}
